project_name: kook

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    binary: kook

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

nfpms:
  - package_name: kook
    vendor: Florian Varrin
    homepage: https://github.com/Florian-Varrin/Kook-cli
    maintainer: Florian Varrin <your.email@example.com>
    description: A simple, powerful CLI task runner configured via Kookfile
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/kook/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/kook/LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Florian-Varrin
    name: Kook-cli
  draft: false
  # GoReleaser automatically marks as pre-release if version contains: alpha, beta, rc
  prerelease: auto
  # Optionally, make latest release point only to stable versions
  make_latest: true